### ISSUE TITLE
unable to install script on fresh install

### ISSUE THREAD

**Issue by nn0de** [IAmStoxe/wirehole#101]
I am trying to install the script on a fresh install of raspberry pi os 64 bit and am being met with errors. I am not experienced enough to figure this out and can not find any useful information to fix my issue. 

I am creating a install.sh file and pasting in the install script
sudo chmod +x install.sh
sudo ./install.sh

and can not get it to run properly. I had cloned the repository separately and it just seems to be running a whole mess. could anyone assist me here?
also no idea what IP it is referencing cause it aint mine ahaha

Get:1 file:/var/cache/openmediavault/archives InRelease
Ign:1 file:/var/cache/openmediavault/archives InRelease
Get:2 file:/var/cache/openmediavault/archives Release
Ign:2 file:/var/cache/openmediavault/archives Release
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Hit:5 https://openmediavault.github.io/packages shaitan InRelease
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease
Hit:7 http://deb.debian.org/debian bullseye InRelease
Hit:8 http://deb.debian.org/debian bullseye-updates InRelease
Hit:9 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
Ign:10 https://download.docker.com/linux/ubuntu bullseye InRelease
Hit:11 https://download.docker.com/linux/debian bullseye InRelease
Hit:12 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:13 http://packages.openmediavault.org/public shaitan InRelease
Err:14 https://download.docker.com/linux/ubuntu bullseye Release
 404 Not Found [IP: 65.8.134.75 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 file:/var/cache/openmediavault/archives InRelease
Ign:1 file:/var/cache/openmediavault/archives InRelease
Get:2 file:/var/cache/openmediavault/archives Release
Ign:2 file:/var/cache/openmediavault/archives Release
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Get:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Translation-en
Ign:4 file:/var/cache/openmediavault/archives Translation-en
Hit:5 http://deb.debian.org/debian bullseye InRelease
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease
Hit:7 http://deb.debian.org/debian bullseye-updates InRelease
Hit:8 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
Hit:9 https://openmediavault.github.io/packages shaitan InRelease
Ign:10 https://download.docker.com/linux/ubuntu bullseye InRelease
Hit:11 https://download.docker.com/linux/debian bullseye InRelease
Hit:12 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:13 http://packages.openmediavault.org/public shaitan InRelease
Err:14 https://download.docker.com/linux/ubuntu bullseye Release
 404 Not Found [IP: 65.8.134.75 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
 % Total % Received % Xferd Average Speed Time Time Time Current
 Dload Upload Total Spent Left Speed
100 9 0 9 0 0 24 0 --:--:-- --:--:-- --:--:-- 24
ln: failed to create symbolic link '/usr/bin/docker-compose': File exists
Cloning into 'wirehole'...
remote: Enumerating objects: 179, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 179 (delta 76), reused 48 (delta 48), pack-reused 84
Receiving objects: 100% (179/179), 111.38 KiB | 2.32 MiB/s, done.
Resolving deltas: 100% (90/90), done.
/usr/local/bin/docker-compose: line 1: Not: command not found

**Comment by IAmStoxe** [comment]
Use the docker install script from docker.io

**Comment by nn0de** [comment]
tremendous help. thank you..
