### ISSUE TITLE
fresh install and old installs with fresh updates becomes not working

### ISSUE THREAD

**Issue by KvizadSaderah** [IAmStoxe/wirehole#102]
i've got peer's endpoints looking like that

```
Endpoint = :51820
```

in case i'm putting server ip in it, as it should be, still not helping...

where should i also perform changes? :(

**Comment by KvizadSaderah** [comment]
anyone have ideas/solutions?

**Comment by garryfreeman** [comment]
were you able to solve the problem?

**Comment by KvizadSaderah** [comment]
I would try it!

**Comment by rtnkv** [comment]
YES! Thank you sir!

**Comment by KvizadSaderah** [comment]
> ```
>    unbound:
> -    image: "mvance/unbound:latest"
> +    image: "mvance/unbound:1.12.0"
>      container_name: unbound
>      restart: unless-stopped
>      hostname: "unbound"
> ```
> 
> 
>     
>   
> 
> this changes in **docker-compose.yml** helped me

IT WORKED! Thank you sir!
