### ISSUE TITLE
Unbound Broken

### ISSUE THREAD

**Issue by NOXCIS** [IAmStoxe/wirehole#104]
The latest mvance unbound image is incompatible with the project see [Worm-Hole](https://github.com/NOXCIS/Worm-Hole) for fix.

**Comment by jimaldon** [comment]
Can confirm. Is your solution to use `klutchell/unbound:latest` instead?

**Comment by NOXCIS** [comment]
Yup

**Comment by jimaldon** [comment]
I just built `mvance:unbound` for `linux/arm64/v8` or my raspberry pi 4 instead: 

`docker pull jimaldon/unbound-pi:latest`

**Comment by NOXCIS** [comment]
If that works go for i, my problem was I didn't want to be a maintainer because I'm still a student.

**Comment by NOXCIS** [comment]
You should also test if unbound is actually working not if unbound is just running.

**Comment by llamaonduty** [comment]
Just want to share that I made https://github.com/guardllamanet/guardllama to address similar problems (WireGuard VPN + AdGuardHome + Unbound). Feel free to try it out if it's a good fit 😄

**Comment by NOXCIS** [comment]
@llamaonduty think log less by design and as a first hop ISP dns bypass.
