### ISSUE TITLE
Restrict PiHole to WireGuard Traffic

### ISSUE THREAD

**Issue by pltrant** [IAmStoxe/wirehole#13]
Is there any option to restrict PiHole to WireGuard traffic only?  Specifically, so that running it has no impact on other processes on the server.

**Comment by IAmStoxe** [comment]
Are you asking to restrict wireguard traffic to only dns traffic? That's covered in the `readme` under split tunnel near the bottom.


 
Or are you asking how to only allow access to pihole over wire guard? If you use the default setup this is the case. Being that it's a docker network it's. Segregated somewhat from your network other than the WG port exposure.

P.s. you can have pihole only listen on that one interface, usually `wg0`. That's done in the admin console of Pihole under DNS.

**Comment by IAmStoxe** [comment]
Ah I see you closed it
