### ISSUE TITLE
How do you add a new wireguard peer?

### ISSUE THREAD

**Issue by Kedstar99** [IAmStoxe/wirehole#2]

**Comment by IAmStoxe** [comment]
I just tested this by creating a single config and connecting to it from another client. I then did the below steps and after the config I made first was still valid and working. It didn't regenerate the existing configurations as one would likely hope. 


Bring down the containers with `docker-compose stop` and let it all gracefully stop.

Edit `docker-compose.yml` under `wireguard`'s environment variables.

Modify the value of "`PEERS=`" to the new value of peers you want. 
```
- PEERS=2 # How many peers to generate for you (clients)
```

Save and close this file.


Then just another `docker-compose up` and it will generate the new configs:

```bash
wireguard    | **** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of XX.XX.XX.XX ****
wireguard    | **** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
wireguard    | **** Internal subnet is set to 10.6.0.0 ****
wireguard    | **** Peer DNS servers will be set to 10.2.0.100 ****
wireguard    | **** Server mode is selected ****
wireguard    | **** Server related environment variables changed, regenerating 1 server and 2 peer/client confs ****
```
