### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by pltrant** [IAmStoxe/wirehole#20]
How do you upgrade when new releases of PiHole, Wireguard, etc become available?

**Comment by IsaSca** [comment]
Wirehole just deploys the pihole, wireguard, and unbound containers. Run something like watchtower to keep everything up to date.

**Comment by IsaSca** [comment]
However, remember to deploy watchtower with edits to interval parameter due to the docker pull rate limits.

**Comment by pltrant** [comment]
I'd mostly just interested in a manual upgrade process at this point.  I did figure out that I can run these commands to update the containers:

`docker pull pihole/pihole
docker pull linuxserver/wireguard
docker pull mvance/unbound
docker-compose down
docker-compose up -d`

Everything then updates and works fine, but it appears the wireguard private/public keys are reset when that happens, so trying to figure out how to maintain those when updating.
