### ISSUE TITLE
Seeing only one client

### ISSUE THREAD

**Issue by roobandev** [IAmStoxe/wirehole#23]
Is it possible to view all the client connected ? It is showing only single client in the dashboard

**Comment by oyren** [comment]
This is because your clients are connected to WireGuard and WireGuard connects to Pi-hole. So the Pi-hole only sees WireGuard as client, I don't think it can be changed.

**Comment by juliangaal** [comment]
> This is because your clients are connected to WireGuard and WireGuard connects to Pi-hole. So the Pi-hole only sees WireGuard as a client, I don't think it is changeable.

Do you know how the author was able to produce [this screenshot](https://github.com/IAmStoxe/oracle-free-tier-wirehole#access-pihole-interface) with "2 Clients"?

**Comment by oyren** [comment]
I am seeing two clients as well, `wireguard.wirehole` and `localhost`.
As already said, your real clients will be hidden behind `wireguard.wirehole`, `localhost` is the machine running Pi-Hole.

**Comment by juliangaal** [comment]
That makes sense.

It would be awesome if this was changable. PiHole 5+ implemented the ability to filter each client individually.

**Comment by sfkds** [comment]
Is it possible to somehow show individual clients? I have another setup without Docker (pihole + wireguard on Raspberry 4 GB)  and there all clients show up individually. but somehow when you user docker it does not seem to work. Wondering if there is something in Network setup in Docker compose that needs to be changed?

**Comment by IAmStoxe** [comment]
Please see updated Readme

**Comment by redex557** [comment]
> Please see updated Readme

At which point did you mention this issue? I read the whole readme and looked at the changelog and did not find anything related...

**Comment by oschmidteu** [comment]
Sorry but where should we look at? I had a Wireguard/PiHole setup running on a NAS in my local Network and all of the Wireguard clients where listed with their WireGuard IPs.
