### ISSUE TITLE
How do I download other peer configs (that do not use QR codes)

### ISSUE THREAD

**Issue by mgrimace** [IAmStoxe/wirehole#25]
Hello and thank you all, I've managed to create new peers for my laptop and desktop. How do I download the config files (since Desktop WireGuard doesn't use QR codes). Thank you!

**Comment by mgrimace** [comment]
For reference, I added peers by opening docker-compose.yml and changing the PEERS value to Peers =imac,air,iphonem,iphonec, windows using `sudo nano /wirehole/docker-compose.yml` then ran this command to recreate WireGuard: `cd /wirehole && sudo docker-compose up --detach`

**Comment by xoniq** [comment]
This part in the compose file:

```yaml
    volumes:      - ./wireguard:/config
```

Defines that the wireguard config folder is mirrored to the folder you ran docker-compose in. (The folder of this project).
So if you go into the projects folder, there should be a new folder 'wireguard' which contains the config files.

**Comment by IAmStoxe** [comment]
Thank you @xoniq!

Please re-open if you have further issues @mgrimace .
