### ISSUE TITLE
Can we setup it on DigitalOcean or Vultr?

### ISSUE THREAD

**Issue by xenstar** [IAmStoxe/wirehole#32]
Do we need to setup it only on oracle? Or Can we setup it on any CloudServer such as Digital Ocean or Vultr?

**Comment by MohamedElashri** [comment]
Yes you can, you can get a new instance with Ubuntu for example and pretty much you can run the bash script in the README. It will handle everything on a fresh installation (updating packages, installing docker and deploying the three wire hole containers) with all the default configuration.  

```
#!/bin/bash

# Prereqs and docker
sudo apt-get update &&
    sudo apt-get install -yqq \
        curl \
        git \
        apt-transport-https \
        ca-certificates \
        gnupg-agent \
        software-properties-common

# Install Docker repository and keys
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable" &&
    sudo apt-get update &&
    sudo apt-get install docker-ce docker-ce-cli containerd.io -yqq

# docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
    sudo chmod +x /usr/local/bin/docker-compose &&
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# wirehole
git clone https://github.com/IAmStoxe/wirehole.git &&
    cd wirehole &&
    docker-compose up
```

you can this as a bash script

use any editor like `nano` or `vim` for example, then write

`nano install.sh`

paste the code above 

you need to give execution permission to this script

`chmod +x install.sh`

Then run the script and wait until everything is ready and your QR will be shown and ready to be used. 

'./install.sh`

PS: if you need more than 1 peer you have to change `PEERS=1` in the `docker-compose.yml` file in the folder `wirehole` which will be created.

**Comment by xenstar** [comment]
Hi Brother

Thank you so much for explaining. I was checking the difference of AdguardHome with Pihole, AdguardHome seems much more easier. Do you have any plan to make a similar version, which is Wireguard + AdguardHome?

Also, traditional VPNs like Wireguard, OpenVPN, can be easily detected by ISP and DPI. There are some new Proxy Technologies, but very powerful such as Vless + tls + Xray or Trojan GFW. You can research it later, and use it as well. 

I am not very good at coding but would like to research new technologies.

**Comment by rumbis** [comment]
i got issues with linode to install that shell on ubuntu 16.04 @MohamedElashri  probably with IP private part with pihole and unbound can you help me solve it or where to edit ip or something? thank you very much
