### ISSUE TITLE
Not working on Raspberry Pi armhf (armv7l) on Buster

### ISSUE THREAD

**Issue by plumped** [IAmStoxe/wirehole#35]
i've been sitting here for hours trying to get this to work.

Processor: BCM2711
Distribution: Raspbian GNU/Linux 10 (buster)
Kernel version: Linux 5.10.17-v7l+ armv7l
Firmware: #1421

Error:
unbound exited with code 1
unbound      | standard_init_linux.go:228: exec user process caused: exec format error

Also the tipp to map other volumes to wireguard volumes did not the trick.
Tipp with Updated Kernel versions - no success

Any ideas?

**Comment by MohamedElashri** [comment]
You will need to build the docker image for `arm`to work. The official one doesn't
