### ISSUE TITLE
Wireguard is connected but IP still stays the same

### ISSUE THREAD

**Issue by scottydelta** [IAmStoxe/wirehole#4]
I have setup the wirehole on an amazon VPC. While I am able to connect to to the instance, I still see my old IP when I goto [whatsmyip.org](https://whatsmyip.org) even though the pihole dashboard is accessible and adblocking seems to be working.

How can I get my server's IP?

**Comment by IAmStoxe** [comment]
That's because you setup a split tunnel as is recommended. You can change that by modifying your wireguard connection to allowed IPs something like `0.0.0.0/0`

**Comment by juliangaal** [comment]
Could you elaborate why Split Tunnel is the recommendation? Why wouldn't I want my entire traffic going through wireguard?
