### ISSUE TITLE
 issues with linode to install that shell on ubuntu 16.04 ip  issue probably 

### ISSUE THREAD

**Issue by rumbis** [IAmStoxe/wirehole#41]
i got issues with linode to install that shell on ubuntu 16.04 @MohamedElashri  probably with IP private part with pihole and unbound can you help me solve it or where to edit ip or something? thank you very much

**Comment by MohamedElashri** [comment]
I would like to help but without description of the problem and hopefully logs, I can't know the problem or give you solution. I also didn't use linode before so don't know about if there is something specific about them but I doubt.
