### ISSUE TITLE
Wireguard UI implementation?

### ISSUE THREAD

**Issue by luximus-hunter** [IAmStoxe/wirehole#43]
Hi. I love what you've done so far. Tho I'd like to see a ui added for the wireguard configs. [Gw-ui](https://github.com/EmbarkStudios/wg-ui) seems like a good option to me. Any chance it will be added?

**Comment by nataliereilly804** [comment]
> ```
> version: "3.8" 
> services:
>   unbound:
>     image: "klutchell/unbound"
>     container_name: unbound
>     restart: unless-stopped
>     hostname: "unbound"
>     ports:
>       - "5053:5053/udp"
>     networks:
>       wg-network:
>         ipv4_address: 10.8.1.10
>   
>   pihole:
>     depends_on: [unbound]
>     container_name: pihole
>     hostname: pihole
>     image: pihole/pihole:latest
>     ports:
>       - "53:53/tcp"
>       - "53:53/udp"
>       - "67:67/udp"
>       - "8080:80/tcp"
>     environment:
>       TZ: 'Europe/Berlin'
>       PIHOLE_DNS_: '10.8.1.10#5053;10.8.1.10#5053' #have to put it in twice :D
>       WEBPASSWORD: 'password'
>     volumes:
>       - ./pihole/etc-pihole:/etc/pihole
>       - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
>     # Recommended but not required (DHCP needs NET_ADMIN)
>     #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
>     cap_add:
>       - NET_ADMIN
>     networks:
>       wg-network:
>         ipv4_address: 10.8.1.20 
>     restart: unless-stopped
>   
>   wg-easy:
>     depends_on: [unbound, pihole]
>     environment:
>       # ⚠️ Required:
>       - WG_HOST=wg.mydomain.tld
>       - PASSWORD=more secret password
>       - WG_PORT=51820
>       #- WG_DEFAULT_ADDRESS=10.8.0.x
>       - WG_DEFAULT_DNS=10.8.1.20, 10.8.1.20
>   
>       - WG_ALLOWED_IPS= 0.0.0.0/1, 10.8.0.0/24, 10.8.1.0/24, 128.0.0.0/2, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.168.1.0/24, 192.168.2.0/23, 192.168.4.0/22, 192.168.8.0/21, 192.168.16.0/20, 192.168.32.0/19, 192.168.64.0/18, 192.168.128.0/17, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/3
>       # figure out what you want to allow and what to block
>       # https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/
>     image: weejewel/wg-easy
>     container_name: wg-easy
>     volumes:
>       - ./wg-easy:/etc/wireguard
>     ports:
>       - "51820:51820/udp"
>       - "8081:51821/tcp" # webinterface
>     restart: unless-stopped
>     cap_add:
>       - NET_ADMIN
>       - SYS_MODULE
>     sysctls:
>       - net.ipv4.ip_forward=1
>       - net.ipv4.conf.all.src_valid_mark=1
>     networks:
>       wg-network:
>         ipv4_address: 10.8.1.30 
> networks:
>   wg-network:
>     ipam:
>       driver: default
>       config:
>         - subnet: 10.8.1.0/24
> ```
> 
> This should get you started

Thanks for your instructions!

**Comment by nataliereilly804** [comment]
@ma-karai Can you help me with Pihole's facility that takes too much time to respond?

**Comment by ma-karai** [comment]
You mean the dns requests are too slow ?
