### ISSUE TITLE
"What is this?" section 

### ISSUE THREAD

**Issue by thomasqbrady** [IAmStoxe/wirehole#6]
A "What is this?" section at the top of the README would be helpful for people who discover this from a link and need some context

**Comment by IAmStoxe** [comment]
Fair point, but is that not what the about section is?

![image](https://user-images.githubusercontent.com/16467875/93121370-9933b580-f679-11ea-8430-f1a72fb6104a.png)

**Comment by IAmStoxe** [comment]
Decided to add it

https://github.com/IAmStoxe/wirehole/blob/master/README.md#what-is-this

**Comment by thomasqbrady** [comment]
Yes, the about section does a pretty good job answering that question, but a lot of people don't notice it up there. It's also helpful to have it locally in the README when you're coming back to a project a few months later and trying to remember what it was. Thanks!

**Comment by IAmStoxe** [comment]
I also noticed on mobile it's rather difficult at times to see the about.

Thanks for opening an issue.
