### ISSUE TITLE
Local DNS resolving on Android

### ISSUE THREAD

**Issue by sudo-meister** [IAmStoxe/wirehole#63]
So, here is the issue ... everything works perfectly fine on my Desktop PC (Linux) and on my iPad. On my Android phone only ad-blocking works, but it doesn't resolve my local DNS records ... I already googled around and it's probably somehow connected to ipv6 on Android

I don't really know where to change what. Can I modify the compose file? Do i nee to change settings in the Unbound or Pi-Hole config?

**Comment by jonny-sexton** [comment]
For mobile clients you most probably need to configure ipv6. See my answer here to see how you can do it: https://github.com/IAmStoxe/wirehole/issues/80#issuecomment-1197057231
