### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JohnFawkes** [IAmStoxe/wirehole#84]
So I want to set this up but switch out pihole for adguard home.  Is this able to provide dns/adblocking without being connected to wireguard on device? Like if I run the docker-compose.yml right now as is, would I be able to still use dns and adblocking by connecting to the dns server via ip?

**Comment by IAmStoxe** [comment]
You'd want to just use pihole by itself. I think this guide will help you.

https://github.com/pi-hole/pi-hole/#one-step-automated-install

**Comment by JohnFawkes** [comment]
I think you misunderstood my question. I still want unbound and wireguard. I just dont want to be 24/7 connected to wireguard. Is wirehole able to do that or do you have to be 24/7 connected to wireguard to get dns/adblocking?
